[options]
HoldPkg     = pacman glibc
Architecture = auto
ILoveCandy
ParallelDownloads = 5
SigLevel = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist

[akspa]
SigLevel = Optional TrustAll
Server = https://pouya3767.github.io/AKSPArepo/x86_64


# [chaotic-aur]
# SigLevel = Never
# Server = https://cdn-mirror.chaotic.cx/chaotic-aur/x86_64
